version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=magento
      - MARIADB_PASSWORD=magento
      - MARIADB_DATABASE=magento
    volumes:
      - 'mariadb_data:/bitnami'
    ports:
      - '3306:3306'
  magento:
    image: 'bitnami/magento:latest'
    labels:
      kompose.service.type: nodeport
    command: "git  clone https://github.com/xdebug/xdebug.git && cd xdebug && chmod 755 ./rebuild.sh && ./rebuild.sh"
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - MAGENTO_DATABASE_USER=magento
      - MAGENTO_DATABASE_PASSWORD=magento
      - MAGENTO_DATABASE_NAME=magento
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - 'magento_data:/bitnami'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  magento_data:
    driver: local
