version: '2'
services:
  app:
    build:
      context: .
      args:
        - WITH_XDEBUG=true
    env_file: .env
    environment:
        - MARIADB_HOST=mariadb
        - MARIADB_PORT_NUMBER=3306
        - MAGENTO_DATABASE_USER=magento
        - MAGENTO_DATABASE_PASSWORD=magento
        - MAGENTO_DATABASE_NAME=magento
        - ELASTICSEARCH_HOST=elasticsearch
        - ELASTICSEARCH_PORT_NUMBER=9200
        - PHP_MEMORY_LIMIT=2048M
        - DEBUG=false
        - ENABLE_SENDMAIL=false
        - UPLOAD_MAX_FILESIZE=64M
        - PHP_ENABLE_XDEBUG=true
    image: xdebug-example:latest
    volumes:
#     - ./app:/var/www/html
     - ./mage:/var/www/html
    ports:
     - "80:80"
    depends_on:
      - mariadb
      - elasticsearch
  mariadb:
    image: 'bitnami/mariadb:10.2'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=magento
      - MARIADB_PASSWORD=magento
      - MARIADB_DATABASE=magento
    volumes:
      - 'mariadb_data:/bitnami'
    ports:
      - '3306:3306'
  elasticsearch:
    image: 'bitnami/elasticsearch:6'
    volumes:
      - 'elasticsearch_data:/bitnami/elasticsearch/data'
volumes:
  elasticsearch_data:
    driver: local
  mariadb_data:
    driver: local
  magento_data:
    driver: local
