#cloud-config
write_files:
-   path: /etc/sudoers.d/999-vagrant-cloud-init-requiretty
    permissions: 440
    content: |
        Defaults:root !requiretty
        Defaults:centos !requiretty
        Defaults:ubuntu !requiretty
        Defaults:admin !requiretty
        Defaults:root !requiretty
        Defaults:fedora !requiretty
        Defaults:ec2-user !requiretty
-   path: /etc/sudoers
    permissions: 440
    content: |
        Defaults:root !requiretty
        Defaults:centos !requiretty
        Defaults:ubuntu !requiretty
        Defaults:admin !requiretty
        Defaults:root !requiretty
        Defaults:fedora !requiretty
        Defaults:ec2-user !requiretty
-   path: /etc/systemd/system/tightvncserver.service
    permissions: 755
    content: |
        [Unit]
        Description=TightVNC remote desktop server
        After=sshd.service
        [Service]
        Type=dbus
        ExecStart=/usr/bin/tightvncserver :1
        User=ec2-user
        Type=forking
        [Install]
        WantedBy=multi-user.target

runcmd:
  - echo '; generated by cloud-init ' > /etc/resolv.conf
  - echo 'nameserver 8.8.8.8' >> /etc/resolv.conf
  - apt-get update
  - apt-get -y install xfce4 xfce4-goodies tightvncserver
  - systemctl enable tightvncserver.service
